# Data parameters
dataset = "lizard"
data_path_liz = "/storage/research/pathology_tru/Elias/other_ds/lizard_5fold_strat_wmit/"
data_path_mit = "/storage/research/pathology_tru/Elias/other_ds/mitosis_ds/"
hard_labels = "/storage/research/pathology_tru/Elias/7class_dist/convnextv2_large_focal_0/"

# Model parameters
encoder = "convnextv2_tiny.fcmae_ft_in22k_in1k" # encoder architecture to use, check 
                                                # https://github.com/huggingface/pytorch-image-models/blob/main/timm/models/convnext.py
out_channels_cls = 8 # fixed for mitosis lizard
inst_channels = 5 # fixed for model 
pretrained = true # use pretrained weights from Timm

# Training parameters

batch_size = 24 # adjust depending on available GPU
validation_batch_size = 64
weight_decay = 0.0001
learning_rate = 0.0001
min_learning_rate = 1e-8
training_steps = 200000
validation_step = 1000
checkpoint_step = 10000
fl_gamma = 2

# Evaluation parameters
tta = 16
eval_optim_metric = "mpq"
n_rounds = 5
save = false # save final predictions on test set
alt_metric_ccrop = 248
match_euc_dist = 6
eval_criteria = "lizard|alt"

# Post-processing
max_hole_size = 50

# Experiment setup

checkpoint_path = ""
experiment = "convnextv2_tiny"
seed = 42
fold = 0
hard = true
test_as_val = true
optim_metric = "mpq" # metric to optimize model for, one of [f1, mpq, pannuke]

# Environment setup

num_workers = 4

# Augmentation parameters
color_scale = 0.4 # simplified multiple parameters by including a scaling factor to increase or reduce augmentation

[aug_params_fast.mirror]
prob_x = 0.5
prob_y = 0.5
prob = 0.5

[aug_params_fast.translate]
max_percent = 0.05
prob = 0.2

[aug_params_fast.scale]
min = 0.8
max = 1.2
prob = 0.2

[aug_params_fast.zoom]
min = 0.5
max = 1.5
prob = 0.2

[aug_params_fast.rotate]
max_degree = 179
prob = 0.75

[aug_params_fast.shear]
max_percent = 0.1
prob = 0.2

[aug_params_fast.elastic]
alpha = [ 120, 120,]
sigma = 8
prob = 0.5
